apiVersion: batch/v1
kind: Job
metadata:
  name: {NAME}
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  backoffLimit: 1  # How many times to try to run the job until giving up
  template:
    metadata:
      generateName: {NAME}
    spec:
      # securityContext:
      #   runAsUser: 1001
      #   runAsGroup: 1001
      priorityClassName: {PRIORITY}
      volumes:
      - name: training
        persistentVolumeClaim:
          claimName: devbox-storage
      containers:
      - name: devbox-container
        image: "ghcr.io/alignmentresearch/acdc:{CONTAINER_TAG}"
        command:
          - bash
          - -c
          - |
            cd /acdc && git fetch && git checkout {COMMIT_HASH} && {COMMAND}
        resources:
          requests:
            cpu: {CPU}
          limits:
            memory: {MEMORY}
            nvidia.com/gpu: {GPU}
        env:
        # credentials for git
        - name: GIT_ASKPASS
          value: "true"
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: pat
        - name: GIT_CONFIG_PARAMETERS
          value: "'credential.https://github.com.username=$(GITHUB_PAT)'"
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb
              key: api-key
        - name: ACDC_OUTPUT_DIR
          value: "/home/dev/acdc_output"
        volumeMounts:
        - name: training
          mountPath: /home/dev
      restartPolicy: Never
      imagePullSecrets:
      - name: docker