defaults:
  - config_schema
  - task: tracr_reverse

num_epochs: 5
wandb_run_name: "${oc.decode:${task.task_name}}_${num_epochs}"
wandb_group_name: !!null

hydra:
  run:
    dir: ${oc.env:ACDC_OUTPUT_DIR, .}/outputs/${now:%Y-%m-%d}-${now:%H%M%S}-${wandb_run_name}
  sweep:
    dir: ${oc.env:ACDC_OUTPUT_DIR, .}/outputs/${now:%Y-%m-%d}-${now:%H%M%S}-${wandb_group_name}
    subdir: ${wandb_run_name}-${hydra:job.name}
